package dev.achmad.finbox.gradle

import com.android.build.api.dsl.ApplicationExtension
import com.android.build.api.variant.ApplicationAndroidComponentsExtension
import org.gradle.api.GradleException
import org.gradle.api.JavaVersion
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure
import org.gradle.kotlin.dsl.create
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.dsl.KotlinAndroidProjectExtension

/**
 * Builds a finbox parser extension APK:
 * - Android application module, no launcher activity
 * - Manifest declares the `dev.achmad.finbox.extension` feature plus
 *   `finbox.extension.lib` metadata and a fixed `finbox.extension.class`,
 *   which the KSP processor in `:compiler` generates from the module's
 *   `@Source` class
 * - Icon comes from the module's own `src/main/res/mipmap-<density>` launcher
 *   icons; the app reads it straight out of the APK
 * - `compileOnly` against the published parser API so the app provides the
 *   real classes at runtime (see the `finbox.apiVersion` gradle property)
 * - Copies the release APK to `repo/apk/finbox-<provider>-<version>.apk`
 */
/**
 * FQN of the class generated by `:compiler` from the module's `@Source` class.
 * Must match GENERATED_PACKAGE/GENERATED_CLASS in SourceProcessor.
 */
private const val GENERATED_CLASS = "dev.achmad.finbox.extension.generated.GeneratedSource"

class FinboxExtensionPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        with(target) {
            // AGP 9 has built-in Kotlin support; no kotlin.android plugin needed.
            pluginManager.apply("com.android.application")
            pluginManager.apply("com.google.devtools.ksp")

            val finbox = extensions.create<FinboxExtension>("finbox")
            val apiVersion = providers.gradleProperty("finbox.apiVersion").orNull
                ?: throw GradleException("finbox.apiVersion must be set in gradle.properties")

            configure<ApplicationExtension> {
                namespace = "dev.achmad.finbox.extension"
                compileSdk = 36
                defaultConfig {
                    minSdk = 26
                    applicationId = "dev.achmad.finbox.extension.${project.name}"
                }
                testOptions {
                    unitTests.isReturnDefaultValues = true
                }
                buildTypes {
                    release {
                        isMinifyEnabled = false
                        signingConfig = signingConfigs.getByName("debug")
                    }
                }
                sourceSets.getByName("main").manifest.srcFile(
                    layout.buildDirectory.file("generated/manifest/AndroidManifest.xml"),
                )
                compileOptions {
                    sourceCompatibility = JavaVersion.VERSION_11
                    targetCompatibility = JavaVersion.VERSION_11
                }
            }

            // defaultConfig is read eagerly, before the finbox {} block is evaluated;
            // the variant API is lazy, so the APK carries the real version rather
            // than a placeholder duplicated into manifest metadata.
            configure<ApplicationAndroidComponentsExtension> {
                onVariants { variant ->
                    variant.outputs.forEach { output ->
                        output.versionCode.set(providers.provider { finbox.versionCode })
                        output.versionName.set(providers.provider { finbox.versionName(apiVersion) })
                    }
                }
            }

            extensions.findByType(KotlinAndroidProjectExtension::class.java)?.compilerOptions {
                jvmTarget.set(JvmTarget.JVM_11)
            }

            val generateManifest = tasks.register("generateFinboxManifest") {
                inputs.property("apiVersion", apiVersion)
                val manifestFile = layout.buildDirectory.file("generated/manifest/AndroidManifest.xml")
                inputs.property("provider", providers.provider { finbox.provider })
                inputs.property("name", providers.provider { finbox.name })
                outputs.file(manifestFile)
                doLast {
                    val file = manifestFile.get().asFile
                    file.parentFile.mkdirs()
                    file.writeText(manifest(finbox, apiVersion))
                }
            }
            tasks.named("preBuild").configure { dependsOn(generateManifest) }

            val copyApk = tasks.register("copyReleaseApk") {
                val apkFile = layout.buildDirectory.file("outputs/apk/release/${project.name}-release.apk")
                val outFile = rootProject.layout.projectDirectory
                    .dir("repo/apk")
                    .file(providers.provider { "finbox-${finbox.provider}-${finbox.versionName(apiVersion)}.apk" })
                inputs.file(apkFile)
                outputs.file(outFile)
                doLast {
                    outFile.get().asFile.parentFile.mkdirs()
                    apkFile.get().asFile.copyTo(outFile.get().asFile, overwrite = true)
                }
            }
            afterEvaluate {
                if (finbox.name.isBlank()) throw GradleException("finbox { name } must be set")
                if (finbox.provider.isBlank()) throw GradleException("finbox { provider } must be set")
                if (finbox.versionCode < 1) throw GradleException("finbox { versionCode } must be >= 1")
                tasks.named("assembleRelease").configure { finalizedBy(copyApk) }
            }

            val deps = dependencies
            deps.add("compileOnly", "com.github.achmadss.finbox-android:extension-api:$apiVersion")
            // The API arrives as a published AAR now, so the stdlib no longer comes
            // along transitively the way a project dependency did. Everything here is
            // compileOnly: the app already ships these at runtime.
            deps.add("compileOnly", "org.jetbrains.kotlin:kotlin-stdlib:2.4.10")
            deps.add("ksp", project(":compiler"))
            // The processor describes the module's main sources. Unit tests hold no
            // @Source class, so running it there would only fail the build.
            tasks.matching { it.name.startsWith("ksp") && it.name.contains("UnitTest") }
                .configureEach { enabled = false }
            deps.add("compileOnly", "com.squareup.okhttp3:okhttp:5.1.0")
            deps.add("compileOnly", "org.jsoup:jsoup:1.18.3")
            deps.add("compileOnly", "org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
            deps.add("compileOnly", "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")

            // Unit tests run on the JVM without the app, so what is compileOnly above
            // has to be a real dependency here.
            deps.add("testImplementation", "com.github.achmadss.finbox-android:extension-api:$apiVersion")
            deps.add("testImplementation", "org.jetbrains.kotlin:kotlin-stdlib:2.4.10")
            deps.add("testImplementation", "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
            deps.add("testImplementation", "org.jsoup:jsoup:1.18.3")
            deps.add("testImplementation", "junit:junit:4.13.2")
        }
    }

    private fun manifest(finbox: FinboxExtension, apiVersion: String): String = """
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android">
            <uses-feature
                android:name="dev.achmad.finbox.extension"
                android:required="true" />
            <application android:icon="@mipmap/ic_launcher">
                <meta-data
                    android:name="finbox.extension.lib"
                    android:value="$apiVersion" />
                <meta-data
                    android:name="finbox.extension.class"
                    android:value="$GENERATED_CLASS" />
                <meta-data
                    android:name="finbox.extension.provider"
                    android:value="${finbox.provider}" />
                <meta-data
                    android:name="finbox.extension.name"
                    android:value="${finbox.name}" />
            </application>
        </manifest>
    """.trimIndent()
}
